### PR TITLE
[IMP]: Added Help Option and Updated indent as per PEP8

### PR DESCRIPTION
**Pull request by srcecde**
Hi,

I have added the HELP option as it was not coded and fixed the indentation as per the PEP8 standards

### CODE REVIEW

**Comment by cosme12** [comment]
Awesome job @srcecde !! It looks great. Thanks for the help. Just one thing, could you change the pull request so it's send to the `develop` branch insteed of master? I'm doing all changes in `develop` and then push all to master as a new release.
Thanks again.

**Comment by srcecde** [comment]
Hi @cosme12 

Can you please give me the location of the develop branch, so that i can push changes to develop branch?

**Comment by cosme12** [comment]
Here is it: https://github.com/cosme12/cheatsheet-maker/tree/develop
I think you can click "Edit" on top and correct it from there

**Comment by srcecde** [comment]
I edited from above and changed the branch to `develop`. But while pushing commit to the develop branch i am getting 403 (permission denied) error.

**Pull request merged**
